package com.example.lenovo.day1.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.day1.Been.BeenDao;

import com.example.lenovo.day1.dao.BeenDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beenDaoDaoConfig;

    private final BeenDaoDao beenDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beenDaoDaoConfig = daoConfigMap.get(BeenDaoDao.class).clone();
        beenDaoDaoConfig.initIdentityScope(type);

        beenDaoDao = new BeenDaoDao(beenDaoDaoConfig, this);

        registerDao(BeenDao.class, beenDaoDao);
    }
    
    public void clear() {
        beenDaoDaoConfig.clearIdentityScope();
    }

    public BeenDaoDao getBeenDaoDao() {
        return beenDaoDao;
    }

}
